### ISSUE TITLE
Explanation on routing through VETH

### ISSUE THREAD

**Issue by Spaider** [belykhk/mikrotik-ovpn-client-tls-crypt#1]
Thanks for the idea. I was able to build an image and now OpenVPN container is up and running.
Would you be so kind and extend the documentation a bit with explanation how to setup RouterOS in order to use `tun0` inside container to route traffic through?

Thanks in advance.

BTW, if OpenVPN server asks for credentials, then a few additional steps would be required:
* Put your credentials in a separate file, let's say `creds.txt`. There should be two lines in there:
   ```
    <your login>
    <your password>
   ``` 
* Edit `client.ovpn` file and add the following line:
   ```
   auth-user-pass /etc/openvpn/creds.txt
   ```
* Edit `Dockerfile` and add `creds.txt` into image:
   ```
   COPY creds.txt   /etc/openvpn/creds.txt
   ```

**Comment by belykhk** [comment]
Hello @Spaider,

I intentionally didn't create any detailed instructions about how to use it, because the intent of this repo is basic idea, which you can expand on. Other reason is that everyone's installation of Mikrotik is different and i'm too lazy to try catch every possible way to use this container.

> how to setup RouterOS in order to use tun0 inside container to route traffic through

The most basic way to use it is create static routes to networks you need to access through container's ip, eg:

```
/ip route add disabled=no distance=<less than main route> dst-address=<target network> gateway=<container ip>
```
___

I will close this issue as won't fix, but feel free to create PR to update README.md or fork this repo and modify it to fit your needs and vision.

**Comment by Spaider** [comment]
I'm sorry, but let me ask you one more question: does this really works, when there's route to `veth` interface? I must be missing something, obviously. As per my understanding, `veth` interface is "mapped" into "eth" interface inside container. `tun0` interface is another interface (set as default gateway after connection via OpenVPN is established). What I do not understand, why input packets for `eth` should be forwarded to `tun0`? Is it certain, that no more actions required _inside_ container?

Thanks!

**Comment by belykhk** [comment]
> does this really works, when there's route to veth interface

Not sure about route to veth interface, I'm using veth's ip address.

When you connecting to OpenVPN server, server will, if configured, push routes to vpn client. You can check it via `ip route` from shell of container (if not, you will need to modify entrypoint to create these routes). 

> What I do not understand, why input packets for eth should be forwarded to tun0?

Container receives packets for destination X, looks at it's own routing table and decides where to forward them. If destination is behind tun0 interface, it will forward it there with masquerading [applied](https://github.com/belykhk/mikrotik-ovpn-client-tls-crypt/blob/4c19d6ad5ad084ba76f3e9c6de3d6563f412cfa8/openvpn-start.sh#L7)
